# https://github.com/kubernetes/ingress-nginx/blob/helm-chart-4.8.3/charts/ingress-nginx/values.yaml
controller:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  autoscaling:
    enabled: "true"
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  config:
    body-size: "0"
    hsts-include-subdomains: "true"
    hsts-max-age: "63072000"
    hsts-preload: "true"
    proxy-body-size: "0"
    proxy-buffer-size: "128k"
    proxy-connect-timeout: "15"
    proxy-read-timeout: "600"
    proxy-send-timeout: "600"
    server-name-hash-bucket-size: "256"
    ssl-reject-handshake: "true"
  service:
    externalTrafficPolicy: "Local"
defaultBackend:
  enabled: true

